apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30021
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations: 
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - name: ftps
      port: 21
      targetPort: 21
      protocol: TCP
    - name: passmin
      port: 30020
      protocol: TCP
    - name: passmax
      port: 30021
      protocol: TCP
  type: LoadBalancer
